### ISSUE TITLE
No update on proceeded to next round

### ISSUE THREAD

**Issue by bodroghtd** [fabrice404/olympics-calendar#12]
If a player proceeds to the next round in a kick-off tournament, the new event is not seen in the calendar

**Comment by fabrice404** [comment]
Do you have an example? I've checked with rugby seven and it was working perfectly.

**Comment by fabrice404** [comment]
I don't see any issue with fencing calendar, there are multiple French competing in fencing today and the calendar update as expected.

**Comment by fabrice404** [comment]
Can you see them here: https://fabrice404.github.io/olympics-calendar/today.html?noc=HUN ?

**Comment by bodroghtd** [comment]
yes, both will start at 15:55

**Comment by fabrice404** [comment]
OK, so there's no issue on my side then, the calendars are correctly updated. I guess your calendar app doesn't update events often enough.

**Comment by bodroghtd** [comment]
Yepp, that's my guess too, cause i tried it on different calendar app, and it works just fine (just realized that after creating this issue)
Btw. nice project, happy to use this :)
