### ISSUE TITLE
Trampoline Gymnastics event shows wrong finalists

### ISSUE THREAD

**Issue by ishaan-mehta** [fabrice404/olympics-calendar#14]
![image](https://github.com/user-attachments/assets/e66613b2-0427-41ca-b259-b5b8834cc3a5)

This shows one athlete who was not part of the Final and excludes one athlete who was part of the Final.

**Comment by fabrice404** [comment]
Thanks for reporting the issue, it was missing the olympic champion from American Samoa `Ivan LITVINOVICH`, I fixed this.

For the two other athletes, they are on the starting list I extract from the official website. I can't really do anything about this.

**Comment by ishaan-mehta** [comment]
Hi @fabrice404, thanks for looking into it! However, I notice that there are 16 entrants on the official website, but only 8 were pulled.

https://olympics.com/en/paris-2024/entries/trampoline-gymnastics/all-noc/men

**Comment by fabrice404** [comment]
I count 16 for the qualification 
<img width="570" alt="Screenshot 2024-08-04 at 21 09 38" src="https://github.com/user-attachments/assets/a5c2df34-23a2-4385-af7e-eb055509ad87">

and 10 for the finals
<img width="595" alt="Screenshot 2024-08-04 at 21 10 39" src="https://github.com/user-attachments/assets/b62519ae-2fc4-47e5-b684-d04c45403dff">

**Comment by ishaan-mehta** [comment]
Interesting, where are you seeing that list for the final? Do you mind sharing the link?

**Comment by fabrice404** [comment]
Here's one of the ics file that shows the competitors: https://github.com/fabrice404/olympics-calendar/blob/main/docs/trampoline-gymnastics/general.ics#L33-L55

The file I took previous post screenshots is available here: https://github.com/fabrice404/olympics-calendar/blob/main/docs/today.html
