### ISSUE TITLE
[Question] Paralympics ?

### ISSUE THREAD

**Issue by flohw** [fabrice404/olympics-calendar#15]
Hi,

I was wondering if the calendar will work for the Paralympic events.

Thanks

**Comment by fabrice404** [comment]
I don't know yet if the website will be the same for the paralympics, but I will definitely try to adapt the code if possible

**Comment by flohw** [comment]
That's what I thought. I will keep an eye on the website.
Thanks! Great Initiative! 🙏

**Comment by fabrice404** [comment]
I've looked into it, and it seems that the paralympics website is in the same old version as the olympics one, which was upgraded on the 18th of July.

My guess is that they will apply the same update before the paralympics starts, so I'll wait until a few days before the opening ceremony (like the 25th of July) before trying to generate the calendars.
