### ISSUE TITLE
Full calendar (all sports, all countries)

### ISSUE THREAD

**Issue by alexture** [fabrice404/olympics-calendar#3]
First of all, thank you, this is AMAZING. You did an excellent job.

Second: could you please add a full calendar at the end, without having to choose a single country (as I suppose choosing a country would remove all individual events)? It would allow to wake up in the morning and immediately see everything that's scheduled for that day!

**Comment by fabrice404** [comment]
Thanks for the support, I can definitely add a calendar for all events, it would be huge though.

When the official website will start to put competitors in different calendars, they should start to appear on the country's (national olympic committee) calendar, like beach volley duos appear already.

**Comment by fabrice404** [comment]
I've added the full calendar, I find it really difficult to read, and my gcal was quite slow, there are more than 2400 events.

week view:
![Screenshot 2024-07-21 at 09 22 44](https://github.com/user-attachments/assets/24995e0a-2457-4bbf-b67b-7321982a1622)

day view:
![Screenshot 2024-07-21 at 09 23 19](https://github.com/user-attachments/assets/9fefaf1c-a7d9-4224-a455-3cf1246f84ea)

schedule view:
![Screenshot 2024-07-21 at 09 23 31](https://github.com/user-attachments/assets/eeeccc4d-1b2a-4ae8-8065-5bc7b82f876e)

**Comment by alexture** [comment]
Ohh! Then that solves it too! I was wondering why the French Beach volley players were showing up haha. Thanks for the explanation :)

Dim 21 juil 2024, à 09:59, Fabrice Lamant a écrit :

**Comment by fabrice404** [comment]
They started to add competitors to the schedule, so now in the `All sports - France` calendar, you can see archery and badminton games.
