### ISSUE TITLE
Beach volleyball and Volleyball have the same emoji

### ISSUE THREAD

**Issue by alexture** [fabrice404/olympics-calendar#4]
I'd recommend using :volleyball: :parasol_on_ground: or so to separate them better. 

Small change, though. :)

**Comment by fabrice404** [comment]
I prefer to keep everything with just one emoji, and unfortunately there's no dedicated one for beach volleyball.

It's the same for 3x3 basketball and basketball. And even worst for cycling as BMX, mountain bike, road and track have the exact same one.
