### ISSUE TITLE
Add Ceremonies calendar

### ISSUE THREAD

**Issue by NilsEnevoldsen** [fabrice404/olympics-calendar#5]
Would you consider adding a Ceremonies calendar for the opening and closing ceremonies? "Ceremonies" is often presented on Olympics schedules alongside sports, such as at https://olympics.com/en/paris-2024/schedule/grid.

**Comment by fabrice404** [comment]
I checked the official website, but it doesn’t publish the dates and times for ceremonies like it does for sports events, so I won’t be able to provide that information.

**Comment by fabrice404** [comment]
<img width="419" alt="Screenshot 2024-07-24 at 21 17 34" src="https://github.com/user-attachments/assets/781cd850-a348-4cec-a6b6-9f788c73c6ef">
