### ISSUE TITLE
Only finals calendar

### ISSUE THREAD

**Issue by aviadlevy** [fabrice404/olympics-calendar#6]
It would be nice to have a calendar with only final events, or even more aggregative, so a person can choose a calendar with events above a certain stage.
It can be per sport or even generic for all finals in all sports

**Comment by fabrice404** [comment]
I'll try to see if I can make calendars for only medal events, but I can't guarantee anything

**Comment by fabrice404** [comment]
Medals events are now available:
- For all sports and NOC
- Per sport
- Per NOC
