### ISSUE TITLE
Missing county (Ethiopia)

### ISSUE THREAD

**Issue by Techpolicy** [fabrice404/olympics-calendar#9]
This is a handy idea that is well executed. 

I tried checking for ET/ETH but did not find the ics. Could I be missing its code?

**Comment by fabrice404** [comment]
You can't find Ethiopia calendar yet, as there's no event publish with an Ethiopian athlete yet, once there will be an event, the calendar will be automatically generated.

For reference: https://olympics.com/en/paris-2024/schedule/ethiopia

**Comment by Techpolicy** [comment]
Thank you. This makes sense.

**Comment by fabrice404** [comment]
There's now one event with an Ethiopian competitor, so the calendar has generated: https://fabrice404.github.io/olympics-calendar/general/ETH.ics
